### ISSUE TITLE
Journal

### ISSUE THREAD

**Issue by BiggyBrey** [BiggyBrey/Emotional-Wellness#3]
### Issues:
* User registration and login
* Password encryption
* Session management

### Frontend
* journal pages
  * CREATE ISSUE: **view journal entries**
    * components
      * journal entry
      * journal entries list
        * bulk delete checkbox?
  * CREATE ISSUE: **create/edit journal entry**
    * components:
      * web form: create/edit journal entry
      * Explore: WISYWIG Text Editor (Quill, TinyMCE)
### Backend
* journal model:
  * #4
* user model (one user HAS MANY journal entries):
  * #4
  
#### CREATE ISSUE: API
* GET journal entries for specific user
* DELETE journal entry
* UPDATE journal entry
* POST (create) journal entry
FOR EACH API endpoint:
recommendation: approach api development this way:
1. create mocked route that returns mock data
2. wire it to the backend and then make it return real data
_This way your api and frontend is not immediately dependent on the database having valid data available._

### CREATE ISSUE: Data
* create some sample journal data that fits the Journal data model
* use this sample data for testing your application flows + functionality

#### CREATE ISSUE: Secure storage of journal entries
* encrypt journal entries in database
  * bcrypt?

**Comment by littilemike11** [comment]
backend for journal complete, tho changes may come as development continues
